var SETTINGS = {
  WIDTH : 600,
  HEIGHT : 400,
  BORDER_WIDTH : 10,
  BACKGROUND_COLOR : "#FFFFFF",
  PLAYER : {
    WIDTH : 15,
    HEIGHT : 80,
    GAP : 20
  },
  BALL : {
    WIDTH : 15,
    HEIGHT : 15,
  },
  NET : {
    WIDTH : 6
  },
  SCORE : {
    Y : 50,
    SIZE : 30,
    GAP : 50
  }
};
SETTINGS.CLIENT_SETTINGS = {
  WIDTH : SETTINGS.WIDTH,
  HEIGHT : SETTINGS.HEIGHT,
  BACKGROUND_COLOR : SETTINGS.BACKGROUND_COLOR,
  NET : SETTINGS.NET
};

module.exports = SETTINGS;
