var SETTINGS = {
  WIDTH : 600,
  HEIGHT : 400,
  BORDER_WIDTH : 10,
  BACKGROUND_COLOR : "#FFFFFF",
  PLAYER : {
    WIDTH : 20,
    HEIGHT : 80,
    GAP : 30
  },
  BALL : {
    WIDTH : 15,
    HEIGHT : 15,
  },
  NET : {
    WIDTH : 6
  },
  SCORE : {
    Y : 40,
    SIZE : 30,
    GAP : 50
  },
  EDGE_SHOOT_ANGLE_ADJUST : 10,
  EDGE_ANGLE : 10,
  STRAIGHT_ADJUST : 5,
  STRATGHT_ANGLE : 5,
  GOAL : 5
};
SETTINGS.CLIENT_SETTINGS = {
  WIDTH : SETTINGS.WIDTH,
  HEIGHT : SETTINGS.HEIGHT,
  BORDER_WIDTH : SETTINGS.BORDER_WIDTH,
  BACKGROUND_COLOR : SETTINGS.BACKGROUND_COLOR,
  NET : SETTINGS.NET
};

module.exports = SETTINGS;
